name = "accomplish-pr-PLACEHOLDER-router"
account_id = "ab43a89c284963fce47460305a945611"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[[services]]
binding = "APP_LITE"
service = "accomplish-pr-PLACEHOLDER-lite"

[[services]]
binding = "APP_ENTERPRISE"
service = "accomplish-pr-PLACEHOLDER-enterprise"
